version: 2.1
description: FaunaDB Python Driver Tests

executors:
  core:
    parameters:
      python_version:
        type: string
      version:
        type: enum
        enum: ["stable", "nightly"]
    resource_class: large
    docker:
      - image: circleci/python:<<parameters.python_version>>

      - image: gcr.io/faunadb-cloud/faunadb/enterprise/<<parameters.version>>:latest
        name: core
        auth:
          username: _json_key
          password: $GCR_KEY

    environment:
      FAUNA_ROOT_KEY: secret
      FAUNA_ENDPOINT: http://core:8443

commands:
  build_and_test:
    description: "Run Python tests"
    steps:
      - checkout

      - run:
          name: Install codecov
          command:  |
            pip install codecov

      - run:
          name: Run Tests
          command: |
            mkdir results
            coverage run setup.py test 2>&1 | tee log.txt

      - run:
          name: Gather Results
          when: always
          command: |
            mkdir -p results/
            mv log.txt results/log.txt

      - store_test_results:
          path: results/
        
      - store_artifacts:
          path: results/
          destination: tr1

jobs:
  core-stable-3.8:
    executor:
      name: core
      python_version: "3.8"
      version: stable
    steps:
      - build_and_test

  core-nightly-3.8:
    executor:
      name: core
      python_version: "3.8"
      version: nightly
    steps:
      - build_and_test

  core-stable-3.4:
    executor:
      name: core
      python_version: "3.4"
      version: stable
    steps:
      - build_and_test

  core-nightly-3.4:
    executor:
      name: core
      python_version: "3.4"
      version: nightly
    steps:
      - build_and_test

  core-stable-2.7:
    executor:
      name: core
      python_version: "2.7"
      version: stable
    steps:
      - build_and_test

  core-nightly-2.7:
    executor:
      name: core
      python_version: "2.7"
      version: nightly
    steps:
      - build_and_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - core-stable-3.8:
          context: faunadb-drivers
      - core-nightly-3.8:
          context: faunadb-drivers
      - core-stable-3.4:
          context: faunadb-drivers
      - core-nightly-3.4:
          context: faunadb-drivers
      - core-stable-2.7:
          context: faunadb-drivers
      - core-nightly-2.7:
          context: faunadb-drivers
